/*-----------------------------------------------------------------------------
-- TABLE名          ：作業人員
-- 作成者           ：zenk
-- 作成日           ：2009-03-04
-- 更新履歴         ：2009-11-02
  -----------------------------------------------------------------------------*/
CREATE TABLE  `WORK_STAFF` (
    `DATA_ID`                     BIGINT(8)     NOT NULL                      COMMENT 'データID',
    `WORK_STAFF_ID`               BIGINT(8)     NOT NULL      AUTO_INCREMENT  COMMENT '作業人員ID',
    `WORK_CONTENT_ID`             BIGINT(8)     NOT NULL                      COMMENT '作業内容ID',
    `WORK_BASE_ID`                BIGINT(8)     NOT NULL                      COMMENT '作業拠点ID',
    `WORK_USER_ID`                BIGINT(8)     NOT NULL                      COMMENT '作業者ユーザID',
    `APPROVAL_DIVISION`           VARCHAR(2)                  DEFAULT 'UC'    COMMENT '承認区分',
    `TRANSMISSION_FLAG`           VARCHAR(1)                  DEFAULT 'N'     COMMENT 'メール送信フラグ',
    `CANCEL_DIVISION`             VARCHAR(2)                  DEFAULT 'WR'    COMMENT 'キャンセル区分',
    `WORK_UNIT_PRICE`             INTEGER                     DEFAULT NULL    COMMENT '作業費',
    `EXCESS_AMOUNT`               DOUBLE(10,2)                DEFAULT NULL    COMMENT '超過',
    `BASIC_TIME`                  DOUBLE(6,2)                 DEFAULT NULL    COMMENT '基本時間',
    `BREAK_TIME`                  DOUBLE(6,2)                 DEFAULT NULL    COMMENT '休憩時間',
    `DISPATCH_SCHEDULE_TIMET`     VARCHAR(30)                 DEFAULT NULL    COMMENT '出発予定時間',
    `DISPATCH_STAFF_TIMET`        VARCHAR(30)                 DEFAULT NULL    COMMENT '出発時間（作業者）',
    `ENTERING_SCHEDULE_TIMET`     VARCHAR(30)                 DEFAULT NULL    COMMENT '入店予定時間',
    `ENTERING_STAFF_TIMET`        VARCHAR(30)                 DEFAULT NULL    COMMENT '入店時間（作業者）',
    `ENTERING_MANAGE_TIMET`       VARCHAR(30)                 DEFAULT NULL    COMMENT '入店時間（管理部）',
    `LEAVE_SCHEDULE_TIMET`        VARCHAR(30)                 DEFAULT NULL    COMMENT '退店予定時間',
    `LEAVE_STAFF_TIMET`           VARCHAR(30)                 DEFAULT NULL    COMMENT '退店時間（作業者）',
    `LEAVE_MANAGE_TIMET`          VARCHAR(30)                 DEFAULT NULL    COMMENT '退店時間（管理部）',
    `TRANSPORT_AMOUNT`            INTEGER                     DEFAULT NULL    COMMENT '交通費',
    `OTHER_AMOUNT`                INTEGER                     DEFAULT NULL    COMMENT 'その他手当',
    `REMARKS`                     VARCHAR(150)                DEFAULT NULL    COMMENT '備考',
    `OVERTIME_WORK_AMOUNT`        DOUBLE(10,2)                DEFAULT NULL    COMMENT '残業代',
    `WORK_EXPENSE_AMOUNT_TOTAL`   DOUBLE(10,2)                DEFAULT NULL    COMMENT '作業費合計',
    `PAYMENT_AMOUNT_TOTAL`        INTEGER                     DEFAULT NULL    COMMENT '出金合計',
    `REAL_WORKING_HOURS`          DOUBLE(6,2)                 DEFAULT NULL    COMMENT '実作業時間',
    `REAL_OVERTIME_HOURS`         DOUBLE(6,2)                 DEFAULT NULL    COMMENT '実残業時間',
    `SUPPLIED_AMOUNT_TOTAL`       INTEGER                     DEFAULT NULL    COMMENT '差引支給額',
    `STAFF_STATUS`                VARCHAR(5)    NOT NULL      DEFAULT 'BD'    COMMENT '作業員ステータス',
    `DISPATCH_DELAY_NOTIFIED`     VARCHAR(1)    NOT NULL      DEFAULT 'N'     COMMENT '出発遅延通知',
    `ENTERING_DELAY_NOTIFIED`     VARCHAR(1)    NOT NULL      DEFAULT 'N'     COMMENT '入店遅延通知',
    `LEAVE_DELAY_NOTIFIED`        VARCHAR(1)    NOT NULL      DEFAULT 'N'     COMMENT '退店遅延通知',
    `WORK_UNIT_PRICE_DISPLAY_FLAG`VARCHAR(1)                  DEFAULT 'Y'     COMMENT '作業費表示フラグ',
    `RESERVE_1`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備1',
    `RESERVE_2`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備2',
    `RESERVE_3`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備3',
    `RESERVE_4`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備4',
    `RESERVE_5`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備5',
    `RESERVE_6`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備6',
    `RESERVE_7`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備7',
    `RESERVE_8`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備8',
    `RESERVE_9`                   VARCHAR(150)                DEFAULT NULL    COMMENT '予備9',
    `RESERVE_10`                  VARCHAR(150)                DEFAULT NULL    COMMENT '予備10',
    `VALIDITY_FLAG`               VARCHAR(1)    NOT NULL       DEFAULT 'Y'    COMMENT '有効フラグ',
    `REGISTRATION_DATET`          DATETIME      NOT NULL                      COMMENT '新規登録日',
    `REGISTRATION_USER_ID`        BIGINT(8)     NOT NULL                      COMMENT '新規登録者ID',
    `LAST_UPDATE_DATET`           DATETIME      NOT NULL                      COMMENT '最終更新日',
    `LAST_UPDATE_USER_ID`         BIGINT(8)     NOT NULL                      COMMENT '最終更新者ID',
   PRIMARY KEY  (`WORK_STAFF_ID`),
    UNIQUE KEY `UI_WORK_STAFF_01` (`DATA_ID`,`WORK_STAFF_ID`,`WORK_CONTENT_ID`),
    UNIQUE KEY `UI_WORK_STAFF_02` (`DATA_ID`,`WORK_STAFF_ID`,`WORK_BASE_ID`),
    UNIQUE KEY `UI_WORK_STAFF_03` (`DATA_ID`,`WORK_STAFF_ID`,`WORK_USER_ID`)
) ENGINE=innoDB DEFAULT CHARSET=utf8 COMMENT='作業人員';
